name: Check that docs are generated

on: push

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup helm-docs action
        uses: gabe565/setup-helm-docs-action@v1

      - name: Create helm docs
        run: |
          helm-docs --skip-version-footer

      - name: Add changes
        run: |
          git add -N .
          git diff --quiet || (echo '::error::Please make sure that the README.md is up to date' && exit 1)
