name: Check that docs are generated

on: push

jobs:
  list-charts:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.charts.outputs.charts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List chart directories
        id: charts
        run: |
          charts=$(ls charts)
          echo "Found charts: $charts"
          echo "charts=$charts" >> $GITHUB_OUTPUT

  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: ${{ fromJson(needs.list-charts.outputs.charts) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup helm-docs action
        uses: gabe565/setup-helm-docs-action@v1

      - name: Create helm docs
        working-directory: "./charts/${{ matrix.chart }}"
        run: |
          helm-docs

      - name: Delete last line and remove helm docs version
        working-directory: "./charts/${{ matrix.chart }}"
        run: |
          find . -type f -name README.md -exec sed -i '$ d' {} \;

      - name: Add changes
        run: |
          git add -N .
          git diff --quiet || (echo '::error::Please make sure that the README.md is up to date' && exit 1)
